----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "koKR" then
    return
end

BTWQUESTS_GIFT_OF_NZOTH = "느조스의 선물"
BTWQUESTS_HATI_REBORN = "다시 태어난 하티"
BTWQUESTS_HERITAGE_OF_THE_BRONZEBEARD = "브론즈비어드의 유산"
BTWQUESTS_HERITAGE_OF_THE_SINDOREI = "신도레이의 유산"
BTWQUESTS_MAGHAR_ORC = "마그하르 오크"
BTWQUESTS_NIGHT_WARRIOR_NIGHT_ELF_CUSTOMIZATION = "나이트 엘프 '밤 전사' 외형"
BTWQUESTS_THE_WAR_CAMPAIGN = "전쟁 대장정"
BTWQUESTS_THE_WAR_CAMPAIGN_8_1 = "전쟁 대장정: 다자알로 전투"
BTWQUESTS_WARFRONT_THE_BATTLE_FOR_DARKSHORE = "격전지: 격전의 어둠해안"
