----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "frFR" then
    return
end

BTWQUESTS_ACTIVE = "Actif"
BTWQUESTS_ALLIED_RACES = "Races alliées "
BTWQUESTS_AVAILABLE = "Disponible"
BTWQUESTS_COMPLETED = "Achevé"
BTWQUESTS_EXPANSION_NAME0 = "World of Warcraft"
BTWQUESTS_EXPANSION_NAME6 = "Legion"
BTWQUESTS_EXPANSION_NAME7 = "Battle for Azeroth"
BTWQUESTS_IGNORED = "Ignoré"
BTWQUESTS_LEVEL = "Niveau %d"
BTWQUESTS_PET = "Familier"
BTWQUESTS_PROFESSIONS = "Métiers"
BTWQUESTS_PROFESSION_ALCHEMY = "Alchimie"
BTWQUESTS_PROFESSION_BLACKSMITHING = "Forge"
BTWQUESTS_PROFESSION_ENCHANTING = "Enchantement"
BTWQUESTS_PROFESSION_ENGINEERING = "Ingénierie"
BTWQUESTS_PROFESSION_FIRST_AID = "Secourisme"
BTWQUESTS_PROFESSION_FISHING = "Pêche"
BTWQUESTS_PROFESSION_HERBALISM = "Herboristerie"
BTWQUESTS_PROFESSION_INSCRIPTION = "Calligraphie"
BTWQUESTS_PROFESSION_JEWELCRAFTING = "Joaillerie"
BTWQUESTS_PROFESSION_LEATHERWORKING = "Travail du cuir"
BTWQUESTS_PROFESSION_MINING = "Minage"
BTWQUESTS_PROFESSION_SKINNING = "Dépeçage"
BTWQUESTS_PROFESSION_TAILORING = "Couture"
BTWQUESTS_TOY = "Jouet"
