----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhCN" then
    return
end

BTWQUESTS_ACTIVE = "使用中"
BTWQUESTS_ALLIED_RACES = "同盟种族"
BTWQUESTS_AVAILABLE = "可用"
BTWQUESTS_COMPLETED = "已完成"
BTWQUESTS_EXPANSION_NAME0 = "经典旧世"
BTWQUESTS_EXPANSION_NAME6 = "军团再临"
BTWQUESTS_EXPANSION_NAME7 = "争霸艾泽拉斯"
BTWQUESTS_IGNORED = "已屏蔽"
BTWQUESTS_LEVEL = "等级%d"
BTWQUESTS_PET = "宠物"
BTWQUESTS_PREFIX = "%s：%s"
BTWQUESTS_PROFESSIONS = "专业"
BTWQUESTS_PROFESSION_ALCHEMY = "炼金术"
BTWQUESTS_PROFESSION_BLACKSMITHING = "锻造"
BTWQUESTS_PROFESSION_ENCHANTING = "附魔"
BTWQUESTS_PROFESSION_ENGINEERING = "工程学"
BTWQUESTS_PROFESSION_FIRST_AID = "急救"
BTWQUESTS_PROFESSION_FISHING = "钓鱼"
BTWQUESTS_PROFESSION_HERBALISM = "草药学"
BTWQUESTS_PROFESSION_INSCRIPTION = "铭文"
BTWQUESTS_PROFESSION_JEWELCRAFTING = "珠宝加工"
BTWQUESTS_PROFESSION_LEATHERWORKING = "制皮"
BTWQUESTS_PROFESSION_MINING = "采矿"
BTWQUESTS_PROFESSION_SKINNING = "剥皮"
BTWQUESTS_PROFESSION_TAILORING = "裁缝"
BTWQUESTS_TOY = "玩具"
