----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "itIT" then
    return
end

BTWQUESTS_ACTIVE = "Attivo"
BTWQUESTS_ALLIED_RACES = "Razze Alleate"
BTWQUESTS_AVAILABLE = "Disponibile"
BTWQUESTS_COMPLETED = "Completo"
BTWQUESTS_EXPANSION_NAME0 = "World of Warcraft"
BTWQUESTS_EXPANSION_NAME6 = "Legion"
BTWQUESTS_EXPANSION_NAME7 = "Battle for Azeroth"
BTWQUESTS_IGNORED = "Ignorato"
BTWQUESTS_LEVEL = "Livello %d"
BTWQUESTS_PET = "Famiglio"
BTWQUESTS_PROFESSIONS = "Professioni"
BTWQUESTS_PROFESSION_ALCHEMY = "Alchimia"
BTWQUESTS_PROFESSION_BLACKSMITHING = "Forgiatura"
BTWQUESTS_PROFESSION_ENCHANTING = "Incantamento"
BTWQUESTS_PROFESSION_ENGINEERING = "Ingegneria"
BTWQUESTS_PROFESSION_FIRST_AID = "Primo Soccorso"
BTWQUESTS_PROFESSION_FISHING = "Pesca"
BTWQUESTS_PROFESSION_HERBALISM = "Erbalismo"
BTWQUESTS_PROFESSION_INSCRIPTION = "Runografia"
BTWQUESTS_PROFESSION_JEWELCRAFTING = "Oreficeria"
BTWQUESTS_PROFESSION_LEATHERWORKING = "Conciatura"
BTWQUESTS_PROFESSION_MINING = "Estrazione"
BTWQUESTS_PROFESSION_SKINNING = "Scuoiatura"
BTWQUESTS_PROFESSION_TAILORING = "Sartoria"
BTWQUESTS_TOY = "Giocattolo"
