----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhTW" then
    return
end

BTWQUESTS_ACTIVE = "啟動"
BTWQUESTS_ALLIED_RACES = "同盟種族"
BTWQUESTS_AVAILABLE = "可用"
BTWQUESTS_COMPLETED = "完成"
BTWQUESTS_EXPANSION_NAME0 = "艾澤拉斯"
BTWQUESTS_EXPANSION_NAME6 = "軍臨天下"
BTWQUESTS_EXPANSION_NAME7 = "決戰艾澤拉斯"
BTWQUESTS_IGNORED = "已忽略"
BTWQUESTS_LEVEL = "等級%d"
BTWQUESTS_PET = "寵物"
BTWQUESTS_PROFESSIONS = "專業技能"
BTWQUESTS_PROFESSION_ALCHEMY = "鍊金術"
BTWQUESTS_PROFESSION_BLACKSMITHING = "鍛造"
BTWQUESTS_PROFESSION_ENCHANTING = "附魔"
BTWQUESTS_PROFESSION_ENGINEERING = "工程學"
BTWQUESTS_PROFESSION_FIRST_AID = "急救"
BTWQUESTS_PROFESSION_FISHING = "釣魚"
BTWQUESTS_PROFESSION_HERBALISM = "草藥學"
BTWQUESTS_PROFESSION_INSCRIPTION = "銘文學"
BTWQUESTS_PROFESSION_JEWELCRAFTING = "珠寶設計"
BTWQUESTS_PROFESSION_LEATHERWORKING = "製皮"
BTWQUESTS_PROFESSION_MINING = "採礦"
BTWQUESTS_PROFESSION_SKINNING = "剝皮"
BTWQUESTS_PROFESSION_TAILORING = "裁縫"
BTWQUESTS_TOY = "玩具"
