----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "koKR" then
    return
end

BTWQUESTS_ACTIVE = "활성화"
BTWQUESTS_ALLIED_RACES = "동맹 종족"
BTWQUESTS_AVAILABLE = "사용 가능"
BTWQUESTS_COMPLETED = "완료"
BTWQUESTS_EXPANSION_NAME0 = "오리지널"
BTWQUESTS_EXPANSION_NAME6 = "군단"
BTWQUESTS_EXPANSION_NAME7 = "격전의 아제로스"
BTWQUESTS_IGNORED = "차단"
BTWQUESTS_LEVEL = "%d 레벨"
BTWQUESTS_PET = "소환수"
BTWQUESTS_PROFESSIONS = "전문 기술"
BTWQUESTS_PROFESSION_ALCHEMY = "연금술"
BTWQUESTS_PROFESSION_BLACKSMITHING = "대장기술"
BTWQUESTS_PROFESSION_ENCHANTING = "마법부여"
BTWQUESTS_PROFESSION_ENGINEERING = "기계공학"
BTWQUESTS_PROFESSION_FIRST_AID = "응급치료"
BTWQUESTS_PROFESSION_FISHING = "낚시"
BTWQUESTS_PROFESSION_HERBALISM = "약초채집"
BTWQUESTS_PROFESSION_INSCRIPTION = "주문각인"
BTWQUESTS_PROFESSION_JEWELCRAFTING = "보석세공"
BTWQUESTS_PROFESSION_LEATHERWORKING = "가죽세공"
BTWQUESTS_PROFESSION_MINING = "채광"
BTWQUESTS_PROFESSION_SKINNING = "무두질"
BTWQUESTS_PROFESSION_TAILORING = "재봉술"
BTWQUESTS_TOY = "장난감"
