----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "ptBR" then
    return
end

BTWQUESTS_ACTIVE = "Ativo"
BTWQUESTS_ALLIED_RACES = "Raças Aliadas"
BTWQUESTS_AVAILABLE = "Disponíveis"
BTWQUESTS_COMPLETED = "Concluído"
BTWQUESTS_EXPANSION_NAME0 = "Clássico"
BTWQUESTS_EXPANSION_NAME6 = "Legion"
BTWQUESTS_EXPANSION_NAME7 = "Battle for Azeroth"
BTWQUESTS_IGNORED = "Ignorado"
BTWQUESTS_LEVEL = "Nível %d"
BTWQUESTS_PET = "Ajudante"
BTWQUESTS_PROFESSIONS = "Profissões"
BTWQUESTS_PROFESSION_ALCHEMY = "Alquimia"
BTWQUESTS_PROFESSION_BLACKSMITHING = "Ferraria"
BTWQUESTS_PROFESSION_ENCHANTING = "Encantamento"
BTWQUESTS_PROFESSION_ENGINEERING = "Engenharia"
BTWQUESTS_PROFESSION_FIRST_AID = "Primeiros socorros"
BTWQUESTS_PROFESSION_FISHING = "Pesca"
BTWQUESTS_PROFESSION_HERBALISM = "Herborismo"
BTWQUESTS_PROFESSION_INSCRIPTION = "Escrivania"
BTWQUESTS_PROFESSION_JEWELCRAFTING = "Joalheria"
BTWQUESTS_PROFESSION_LEATHERWORKING = "Couraria"
BTWQUESTS_PROFESSION_MINING = "Mineração"
BTWQUESTS_PROFESSION_SKINNING = "Esfolamento"
BTWQUESTS_PROFESSION_TAILORING = "Alfaiataria"
BTWQUESTS_TOY = "Brinquedo"
