----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "ruRU" then
    return
end

BTWQUESTS_ACTIVE = "Активный"
BTWQUESTS_ALLIED_RACES = "Союзные Расы"
BTWQUESTS_AVAILABLE = "Имеется в наличии"
BTWQUESTS_COMPLETED = "Завершенный"
BTWQUESTS_COSMETIC = "Косметический"
BTWQUESTS_COUNTDOWN_DHM = "%d дней, %d часов и %d минут"
BTWQUESTS_COUNTDOWN_HMS = "%d часов, %d минут и %d секунд"
BTWQUESTS_COUNTDOWN_MS = "%d минут и %d секунд"
BTWQUESTS_COUNTDOWN_S = "%d секунд"
BTWQUESTS_EPILOGUE = "Эпилог"
BTWQUESTS_EXPANSION_NAME0 = "World of Warcraft"
BTWQUESTS_EXPANSION_NAME6 = "Legion"
BTWQUESTS_EXPANSION_NAME7 = "Battle for Azeroth"
BTWQUESTS_GO_TO = "Перейти к %s"
BTWQUESTS_IGNORED = "Игнорируются"
BTWQUESTS_INTRODUCTION = "Вступление"
BTWQUESTS_KILL = "Убить %s"
BTWQUESTS_LEVEL = "Уровень %d"
BTWQUESTS_NO_EXPANSION_ERROR = "[BtWQuests]: Пожалуйста, включите один из аддонов расширения, например, BtWQuests: Battle for Azeroth."
BTWQUESTS_OPEN_QUEST_CHAIN = "Открытая цепочка заданий"
BTWQUESTS_PASSED = "Прошло"
BTWQUESTS_PET = "Питомец"
BTWQUESTS_PROFESSIONS = "Профессии"
BTWQUESTS_PROFESSION_ALCHEMY = "Алхимия"
BTWQUESTS_PROFESSION_BLACKSMITHING = "Кузнечное Дело"
BTWQUESTS_PROFESSION_ENCHANTING = "Наложение Чар"
BTWQUESTS_PROFESSION_ENGINEERING = "Инженерное Дело"
BTWQUESTS_PROFESSION_FIRST_AID = "Первая Помощь"
BTWQUESTS_PROFESSION_FISHING = "Рыбная Ловля"
BTWQUESTS_PROFESSION_HERBALISM = "Травничество"
BTWQUESTS_PROFESSION_INSCRIPTION = "Начертание"
BTWQUESTS_PROFESSION_JEWELCRAFTING = "Ювелирное Дело"
BTWQUESTS_PROFESSION_LEATHERWORKING = "Кожевничество"
BTWQUESTS_PROFESSION_MINING = "Горное Дело"
BTWQUESTS_PROFESSION_SKINNING = "Снятие Шкур"
BTWQUESTS_PROFESSION_TAILORING = "Портняжное Дело"
BTWQUESTS_PROGRESS = "Прогресс %d из %d"
BTWQUESTS_PROGRESS_SIDE = "Прогресс %d из %d (%d из %d)"
BTWQUESTS_PROLOGUE = "Пролог"
BTWQUESTS_QUEST_CHAIN_ACTIVE = "Вы находитесь в этой цепочке заданий"
BTWQUESTS_QUEST_CHAIN_COMPLETED = "Вы завершили эту цепочку заданий"
BTWQUESTS_QUEST_JOURNAL = "Журнал Заданий"
BTWQUESTS_REPUTATION_AMOUNT_STANDING = "%s в %s с %s"
BTWQUESTS_REPUTATION_STANDING = "%s с %s"
BTWQUESTS_REQUIREMENTS = "%d/%d Требования"
BTWQUESTS_REQUIREMENT_PROGRESS = "Требование прогресса"
BTWQUESTS_SECRET = "Секреты"
BTWQUESTS_SIDE_QUESTS = "Побочные задания"
BTWQUESTS_SKILL_LEVEL = "%s в %s"
BTWQUESTS_TOOLTIP_PREREQUISITES = "Предпосылки:"
BTWQUESTS_TOY = "Игрушка"
BTWQUESTS_VIEW_ALL = "Посмотреть все"
