----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "esES" then
    return
end

BTWQUESTS_ACTIVE = "Activo"
BTWQUESTS_ALLIED_RACES = "Razas aliadas"
BTWQUESTS_AVAILABLE = "Disponible"
BTWQUESTS_COMPLETED = "Completado"
BTWQUESTS_EXPANSION_NAME0 = "World of Warcraft: Clásico"
BTWQUESTS_EXPANSION_NAME6 = "Legion"
BTWQUESTS_EXPANSION_NAME7 = "Battle for Azeroth"
BTWQUESTS_IGNORED = "Ignorado"
BTWQUESTS_LEVEL = "Nivel %d"
BTWQUESTS_PET = "Mascota"
BTWQUESTS_PROFESSIONS = "Profesiones"
BTWQUESTS_PROFESSION_ALCHEMY = "Alquimia"
BTWQUESTS_PROFESSION_BLACKSMITHING = "Herrería"
BTWQUESTS_PROFESSION_ENCHANTING = "Encantamiento"
BTWQUESTS_PROFESSION_ENGINEERING = "Ingeniería"
BTWQUESTS_PROFESSION_FIRST_AID = "Primeros auxilios"
BTWQUESTS_PROFESSION_FISHING = "Pesca"
BTWQUESTS_PROFESSION_HERBALISM = "Herboristería"
BTWQUESTS_PROFESSION_INSCRIPTION = "Inscripción"
BTWQUESTS_PROFESSION_JEWELCRAFTING = "Joyería"
BTWQUESTS_PROFESSION_LEATHERWORKING = "Peletería"
BTWQUESTS_PROFESSION_MINING = "Minería"
BTWQUESTS_PROFESSION_SKINNING = "Desuello"
BTWQUESTS_PROFESSION_TAILORING = "Sastrería"
BTWQUESTS_TOY = "Juguete"
