----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "deDE" then
    return
end

BTWQUESTS_ACTIVE = "Aktiv"
BTWQUESTS_ALLIED_RACES = "Verbündete Völker"
BTWQUESTS_AVAILABLE = "Verfügbar"
BTWQUESTS_COMPLETED = "Abgeschlossen"
BTWQUESTS_EXPANSION_NAME0 = "Classic"
BTWQUESTS_EXPANSION_NAME6 = "Legion"
BTWQUESTS_EXPANSION_NAME7 = "Battle for Azeroth"
BTWQUESTS_IGNORED = "Ignoriert"
BTWQUESTS_LEVEL = "Stufe %d"
BTWQUESTS_PET = "Begleiter"
BTWQUESTS_PROFESSIONS = "Berufe"
BTWQUESTS_PROFESSION_ALCHEMY = "Alchemie"
BTWQUESTS_PROFESSION_BLACKSMITHING = "Schmiedekunst"
BTWQUESTS_PROFESSION_ENCHANTING = "Verzauberkunst"
BTWQUESTS_PROFESSION_ENGINEERING = "Ingenieurskunst"
BTWQUESTS_PROFESSION_FIRST_AID = "Erste Hilfe"
BTWQUESTS_PROFESSION_FISHING = "Angeln"
BTWQUESTS_PROFESSION_HERBALISM = "Kräuterkunde"
BTWQUESTS_PROFESSION_INSCRIPTION = "Inschriftenkunde"
BTWQUESTS_PROFESSION_JEWELCRAFTING = "Juwelierskunst"
BTWQUESTS_PROFESSION_LEATHERWORKING = "Lederverarbeitung"
BTWQUESTS_PROFESSION_MINING = "Bergbau"
BTWQUESTS_PROFESSION_SKINNING = "Kürschnerei"
BTWQUESTS_PROFESSION_TAILORING = "Schneiderei"
BTWQUESTS_TOY = "Spielzeug"
