------------------------------------------------------------------------------
-- Rematch_TSMPetValues - Add TSM market values ​​to the Rematch pet list
------------------------------------------------------------------------------
-- PriceSource_TSM.lua - TSM Price Sources
--
-- Author: Expelliarm5s / July 2021 / All Rights Reserved
--
-- Version 1.1.22
------------------------------------------------------------------------------
-- luacheck: ignore 212 globals DLAPI
